# Taylor Rule Implementation of the Fed's Monetary Policy

*A Taylor rule is a monetary policy that stipulates how much the central bank should change the nominal interest rate in response to changes in inflation, output and other economic conditions. It is used to establish the monetary policy rate (federal funds rate for U.S. case). It is part of the debate rules version discretion in monetary theory. Should central banks disclose the algorithm for setting their policy rate or not? There are advantages and disadvantages. Some say that higher transparency may reduce the element of surprise of monetary policy decisions and therefore reduce the impact of them. *


$i_{t} = r^{*} + \pi^{T} + \alpha_{x}x_{t} + \alpha_{\pi}(\pi_{t} - \pi^{T})$
           
           
$i_{t}$ = Federal Funds interest rate in the U.S.

$\pi^{T}$ = Targeted level of average inflation (Taylor asumed it at 2%)

$r^{*}$ = Equilibrium interest rate (Taylor assumed it at 2%)

$x_{t}$ = Output gap (the difference bewteen GDP and potential GDP)

Potential GDP = The output level that does not generate infationary pressures

## The U.S. Potential Gap

Potential GDP is a theoretic concept we can not calculate it directly, we can estimate it. It is that level of output that does not generate inflationary pressures. It is the long-term level of GDP. 

There are different ways of calculating it: stats filters (HP, band pass), DSGE, SVAR, Production Function approach.

**a) FRED Database:** 

http://research.stlouisfed.org/fred2/series/GDPPOT/


**b) Calculate it:** 

Hodrick-Prescott (HP) Statistical Filter

## a) FRED Database

In [0]:
import numpy as np
import statsmodels.api as sm

#Federal funds rate
r=[0.0568, 0.0627, 0.0652, 0.0647, 0.0559, 0.0433, 0.035, 0.0213, 0.0173, 0.0175, 0.0174,
0.0144, 0.0125, 0.0125, 0.0102, 0.01, 0.01, 0.0101, 0.0143, 0.0195, 0.0247, 0.0294, 0.0346,
0.0398, 0.0446, 0.0491, 0.0525, 0.0525, 0.0526, 0.0525, 0.0507, 0.045, 0.0318, 0.0209, 0.0194,
0.0051, 0.0018, 0.0018, 0.0016, 0.0012, 0.0013, 0.0019, 0.0019, 0.0019, 0.0016, 0.0009, 0.0008,
0.0007, 0.001, 0.0015, 0.0014, 0.0016, 0.0014, 0.0012, 0.0008, 0.0009, 0.0007, 0.0009, 0.0009]


## b) Hodrick-Prescott (HP) Statistical Filter:

The Hodrick-Prescott (HP) filter refers to a data-smoothing technique. The HP filter is commonly applied during analysis to remove short-term fluctuations associated with the business cycle. Removal of these short-term fluctuations reveals long-term trends. This can help with economic or other forecasting associated with the business cycle.

This filter determines the long-term trend of a time series by discounting the importance of short-term price fluctuations.

It tends to have favorable results if the noise is distributed normally, and when the analysis being conducted is historical.

### To Calculate Potential Output

GDP is separated into a cyclical and a trend component by minimizing a loss
function.

Takes into consideration time series data (U.S. GDP) and a parameter
lambda – Hodrick-Prescott smoothing parameter. We have to
indicate lambda’s value before the filter calculates the new values. A value of 1600
is suggested for quarterly data. Ravn and Uhlig suggest using a value of 6.25
(1600/256) for annual data and 129600 (1600*81) for monthly data.


In [62]:
import statsmodels.tsa.filters as filter

gdp2=[9.213436, 9.237790, 9.245457, 9.256489, 9.259902, 9.272225, 9.272329,
9.278121, 9.290482, 9.299706, 9.309018, 9.315043, 9.326353, 9.338795, 9.360922,
9.377278, 9.391695, 9.407665, 9.422844, 9.438448, 9.458270, 9.470710, 9.488381,
9.501636, 9.521414, 9.532409, 9.540255, 9.551544, 9.563333, 9.576531, 9.586699,
9.594602, 9.593451, 9.603260, 9.605284, 9.585339, 9.573865, 9.570836, 9.573879,
9.586480, 9.594316, 9.608351, 9.619645, 9.631036, 9.631574, 9.646070, 
9.654199, 9.666834, 9.677622, 9.686245, 9.697011, 9.700912, 9.711261, 9.718314,
9.733429, 9.745564, 9.743554, 9.760091, 9.773105]

filter.hp_filter.hpfilter(gdp2, 1600)

output_gap = filter.hp_filter.hpfilter(gdp2, 1600)[0]
output_gap

array([ 0.00320611,  0.01638169,  0.01286827,  0.01270561,  0.00488941,
        0.00592046, -0.00536153, -0.01108455, -0.01039922, -0.01303624,
       -0.01578882, -0.02204202, -0.02322403, -0.02347425, -0.01421158,
       -0.01084925, -0.00950361, -0.00662421, -0.00449068, -0.0018185 ,
        0.00525666,  0.00520725,  0.01071545,  0.01220017,  0.02065966,
        0.02083949,  0.01841236,  0.01999594,  0.02266136,  0.02731929,
        0.02951823,  0.02999359,  0.02190834,  0.0252097 ,  0.0210722 ,
       -0.00478438, -0.02202943, -0.03079537, -0.03354782, -0.02687418,
       -0.02514988, -0.01744653, -0.01272404, -0.00815343, -0.01468573,
       -0.0075059 , -0.00692572, -0.00205428,  0.00077768,  0.00127567,
        0.00377073, -0.00072288,  0.00112772, -0.00040113,  0.00606821,
        0.00951361, -0.00121383,  0.00658804,  0.01086012])

hpfilter function returns array one and array two:
array one – is the first and represents the cycle array;
array two – is the trend array (estimated potential GDP in our case). Potential GDP
could also be seen as GDP’s long-term trend.

Use the output gap calculated from the filter in the matrix x down below.

In [63]:
import numpy as np
import statsmodels.api as sm

#Federal funds rate
r=[0.0568, 0.0627, 0.0652, 0.0647, 0.0559, 0.0433, 0.035, 0.0213, 0.0173, 0.0175, 0.0174,
0.0144, 0.0125, 0.0125, 0.0102, 0.01, 0.01, 0.0101, 0.0143, 0.0195, 0.0247, 0.0294, 0.0346,
0.0398, 0.0446, 0.0491, 0.0525, 0.0525, 0.0526, 0.0525, 0.0507, 0.045, 0.0318, 0.0209, 0.0194,
0.0051, 0.0018, 0.0018, 0.0016, 0.0012, 0.0013, 0.0019, 0.0019, 0.0019, 0.0016, 0.0009, 0.0008,
0.0007, 0.001, 0.0015, 0.0014, 0.0016, 0.0014, 0.0012, 0.0008, 0.0009, 0.0007, 0.0009, 0.0009]

#Matrix of output gap
x=[[0.012580, 0.012934, 0.014689, 0.014435, 0.014098, 0.013249, 0.006780, -0.001249, -
0.007681, -0.006824, -0.004237, 0.002535, 0.009764, 0.000059, 0.002169, 0.000017, -
0.001823, 0.007859, 0.006752, 0.013851, 0.010354, 0.009229, 0.018196, 0.016745, 0.016909,
0.019243, 0.013403, -0.000346, 0.004315, 0.006651, 0.003488, 0.020315, 0.021372,
0.023106, 0.032525, -0.004042, -0.021842, -0.029423, -0.036070, -0.005125,
0.003369, -0.002141, -0.007713, -0.007845, 0.001211, 0.013752, 0.017318, 
0.013364, 0.008060, -0.000820, -0.003133, -0.000982, -0.003263, -0.005736, -
0.004618, -0.007800, -0.005996, 0.000583, -0.002092], [0.003206, 0.016382,
0.012868, 0.012706, 0.004889, 0.005921, -0.005362, -0.011085, -0.010400, -0.013037, -
0.015789, -0.022042, -0.023224, -0.023474, -0.014212, -0.010850, -0.009504, -0.006624, -
0.004491, -0.001819, 0.005257, 0.005208, 0.010716, 0.012200, 0.020660, 0.020840, 0.018413,
0.019996, 0.022661, 0.027319, 0.029519, 0.029994, 0.021908, 0.025210, 0.021072, -0.004784,
-0.022030, -0.030795, -0.033548, -0.026875, -0.025150, -0.017446, -0.012724, -0.015224, -
0.007616, -0.007506, -0.006926, -0.002054, 0.000837, 0.001276, 0.003770, -0.000723,
0.001128, -0.000401, 0.006068, 0.009514, -0.001214, 0.006588, 0.010861]]


## Define the Taylor Rule Function

The matrix X is made up of two components:

- The Output Gap ( x [ 0 ] ) :
    ln(GDP) - ln(Real Potential GDP)

- Consumer Price Index ( x [ 1 ] ) :
    Percentage change from a year ago done quarterly
    
### Timeframe
 
 1999 Q4 - 2014 Q2

In [52]:
def TaylorRule(r,x):
    
    # Define a column vector of ones with length equal to the length of the rows of x
    ones = np.ones(len(x[0]))
    
    """Column stack is like a cbind() in R"""
    """add_constant is the same as column stack"""
    #Bind the columns with the first row of the matrix X
    X = sm.add_constant(np.column_stack((x[0], ones)))
    
    # Column bind each element of the CPI(x[1:] as an array) to X
    # For loop way of doing it same thing as binding the columns as before
    for element in x[1:]:
        X = sm.add_constant(np.column_stack((element, X)))

    # Run the OLS regression
    results = sm.OLS(r, X).fit()
    return results
    
print(TaylorRule(r,x ).summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.436
Model:                            OLS   Adj. R-squared:                  0.415
Method:                 Least Squares   F-statistic:                     21.61
Date:                Wed, 18 Dec 2019   Prob (F-statistic):           1.11e-07
Time:                        21:23:49   Log-Likelihood:                 160.84
No. Observations:                  59   AIC:                            -315.7
Df Residuals:                      56   BIC:                            -309.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.6859      0.173      3.958      0.0

## Calculating Federal Funds Rate using Taylor Rule

Taylor rules show if the federal funds rate in a certain period is calibrated adequately
considering the inflationary pressures in the economy.

- Obtained without the HP Filter:

$rTaylorRule1=0.6859x1+0.3360x2+0.0191$

- Obtained with the HP Filter:

$rTaylorRule2=-0.1064x1+0.8681x2+0.0090$

## Appendix

Trials I used to better understand the code given

In [12]:
X = sm.add_constant(np.column_stack((x[0], ones)))
X[:5]

array([[0.01258 , 1.      ],
       [0.012934, 1.      ],
       [0.014689, 1.      ],
       [0.014435, 1.      ],
       [0.014098, 1.      ]])

In [14]:
    ones = np.ones(len(x[0]))
    X = np.column_stack((x[0], ones))
    X[:5]

array([[0.01258 , 1.      ],
       [0.012934, 1.      ],
       [0.014689, 1.      ],
       [0.014435, 1.      ],
       [0.014098, 1.      ]])

In [3]:
a = np.array((1,2,3))
b =  np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [47]:
# As an array
x[1:]

[[0.003206,
  0.016382,
  0.012868,
  0.012706,
  0.004889,
  0.005921,
  -0.005362,
  -0.011085,
  -0.0104,
  -0.013037,
  -0.015789,
  -0.022042,
  -0.023224,
  -0.023474,
  -0.014212,
  -0.01085,
  -0.009504,
  -0.006624,
  -0.004491,
  -0.001819,
  0.005257,
  0.005208,
  0.010716,
  0.0122,
  0.02066,
  0.02084,
  0.018413,
  0.019996,
  0.022661,
  0.027319,
  0.029519,
  0.029994,
  0.021908,
  0.02521,
  0.021072,
  -0.004784,
  -0.02203,
  -0.030795,
  -0.033548,
  -0.026875,
  -0.02515,
  -0.017446,
  -0.012724,
  -0.015224,
  -0.007616,
  -0.007506,
  -0.006926,
  -0.002054,
  0.000837,
  0.001276,
  0.00377,
  -0.000723,
  0.001128,
  -0.000401,
  0.006068,
  0.009514,
  -0.001214,
  0.006588,
  0.010861]]

In [48]:
# as a column vector
x[1]

[0.003206,
 0.016382,
 0.012868,
 0.012706,
 0.004889,
 0.005921,
 -0.005362,
 -0.011085,
 -0.0104,
 -0.013037,
 -0.015789,
 -0.022042,
 -0.023224,
 -0.023474,
 -0.014212,
 -0.01085,
 -0.009504,
 -0.006624,
 -0.004491,
 -0.001819,
 0.005257,
 0.005208,
 0.010716,
 0.0122,
 0.02066,
 0.02084,
 0.018413,
 0.019996,
 0.022661,
 0.027319,
 0.029519,
 0.029994,
 0.021908,
 0.02521,
 0.021072,
 -0.004784,
 -0.02203,
 -0.030795,
 -0.033548,
 -0.026875,
 -0.02515,
 -0.017446,
 -0.012724,
 -0.015224,
 -0.007616,
 -0.007506,
 -0.006926,
 -0.002054,
 0.000837,
 0.001276,
 0.00377,
 -0.000723,
 0.001128,
 -0.000401,
 0.006068,
 0.009514,
 -0.001214,
 0.006588,
 0.010861]